import "@/app/globals.css";
import AppWalletProvider from "@/components/AppWalletProvider";
import Header from "@/components/Header";
import Spinner from "@/components/Spinner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Remixers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppWalletProvider>
          <Header />
          <main className="mt-24">{children}</main>
        </AppWalletProvider>
        <Spinner />
      </body>
    </html>
  );
}
